### ISSUE TITLE
cors is blocking 

### ISSUE THREAD

**Issue by eliasayele** [erdkse/adminlte-3-react#38]
Access to XMLHttpRequest at 'https://adminlte-gatekeeper.herokuapp.com/v1/auth/login' from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by erdkse** [comment]
Server API uses free Heroku tier and it is blocked due to its monthly limit. I will move the API server to a new one whenever I find some free time.

**Comment by eliasayele** [comment]
@erdkse ok thanks

**Comment by erdkse** [comment]
You will not see this error from the 1st day of next month. I will also write here when I move API to its new server.
