### ISSUE TITLE
Not working for mobile

### ISSUE THREAD

**Issue by santiagoapp** [erdkse/adminlte-3-react#40]
For some reason the app is not working on mobile, do you know what is happening in this case?

**Comment by erdkse** [comment]
I tested it there is not problem with the mobile. Can you describe more? What kind a problem?

**Comment by santiagoapp** [comment]
> I tested it there is not problem with the mobile. Can you describe more? What kind a problem?

I've realized that the issue was caused because I integrate react-thunk and Redux Developer Tools in composeEnhancers, this is the fix of my project:

On store/index.js:

`import thunkMiddleware from 'redux-thunk';
import {createStore, combineReducers, applyMiddleware, compose} from 'redux';
import authReducer from './reducers/auth';
import menuReducer from './reducers/menu';
import modelReducer from './reducers/model';

const rootReducer = combineReducers({
    auth: authReducer,
    menu: menuReducer,
    appData: modelReducer
});

const composeEnhancers = window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__ || compose;

const store = createStore(
    rootReducer,
    composeEnhancers(applyMiddleware(thunkMiddleware))
);

export default store;`

Thanks dude.
