### ISSUE TITLE
[Question] how to manage adminlte 3 required js files in index.html

### ISSUE THREAD

**Issue by mhanchini** [erdkse/adminlte-3-react#45]
Hi
I looking for adminlte js files <jquery, adminlte.js,demo.js and so on> that usually added in index.html, how to load it without called in index.html or import it in index.js or app.js?

**Comment by erdkse** [comment]
This project is not meant to work with JQuery and only supports React implementation.

If you want a feature to be supported you can create an issue for it and I can take care of it in my free time or just create a PR maybe.

**Comment by mhanchini** [comment]
I see. thank you for your answer.
