### ISSUE TITLE
it doesn't see the axios library.

### ISSUE THREAD

**Issue by fatihdurmaz** [erdkse/adminlte-3-react#51]
hi, i want to use axios in auth.js file but it doesn't see this code.
import {axios} from 'axios';

**Comment by fatihdurmaz** [comment]
I tried this import axios from 'axios';
I get this error.
![Uploading Ekran Alıntısı.PNG…]()

**Comment by erdkse** [comment]
the warning says that you defined it but never used - If you start using it it will disappear - It is a lint error
