### ISSUE TITLE
Strange Horizontal overflow

### ISSUE THREAD

**Issue by Luanr** [erdkse/adminlte-3-react#60]
Whenever the content wrapper gets bigger it appears a strange horizontal overflow. It also happens when you resize the window.

![image](https://user-images.githubusercontent.com/3708982/172728407-5521fc03-80fc-4886-beb6-7ca3abbca21e.png)
Chrome

![image](https://user-images.githubusercontent.com/3708982/172728945-bbf05ebd-3843-4694-944e-fc56c2ed7f64.png)
Firefox

**Comment by erdkse** [comment]
thank you for reporting, I will check it

**Comment by erdkse** [comment]
fixed!
