### ISSUE TITLE
unable to login for testing

### ISSUE THREAD

**Issue by tytx** [erdkse/adminlte-3-react#70]
Hello there, am unable to login to the site as per below

![image](https://user-images.githubusercontent.com/48706492/210976809-e20859b1-7876-4a1f-b507-615c8ad4be43.png)

**Comment by erdkse** [comment]
The server looks up, How did you try to log in, and with which credentials? Anyway you can register with your account information too, please inform me

**Comment by tytx** [comment]
sure, i was trying to login with the "admin@example.com" credentials after forking a copy of this on my local server, how can i manage this user flow locally?

**Comment by erdkse** [comment]
I should work on your local too, it just connects to outer server, everything should be fine.

**Comment by erdkse** [comment]
I dropped usage of a library that causes this issue. You can login now.
