### ISSUE TITLE
.env file doesn't work

### ISSUE THREAD

**Issue by ZePhteven** [erdkse/adminlte-3-react#73]
Hi,

The .env file (I tried other declinations, like .env.local, .env.development) doest seems to work.

Even the `process.env.REACT_APP_USERS_API_URL` you provided is undefined.

Is there something I'm missing ?

Thx

**Comment by erdkse** [comment]
there is no .env file required to run the application. Do you want to use it for your purposes?

**Comment by ZePhteven** [comment]
Oh, yes sorry, there is a `.env.example` wich I tried to use. I'm new to react I understood that this was the proper way to store env values.

It's just that I tried multiples things, like renaming it and I have still no `process.env`.

I don't know, maybe it's not related to you project, I was wondering.

**Comment by erdkse** [comment]
yeah, this project uses default configurations of `CRA`, you can find the documentation here => https://create-react-app.dev/docs/adding-custom-environment-variables/

**Comment by ZePhteven** [comment]
Ok, even though I tried everything. I might be missing something.

Thank's and sorry for that.
