### ISSUE TITLE
Gatekeeper.js cannot update 

### ISSUE THREAD

**Issue by prachaporn** [erdkse/adminlte-3-react#78]
I can't edit anything in this file.
Every time you modify the code, it will run as before.
----------------------------------
`class Gatekeeper {
    constructor() {
        this.LOCALSTORAGE_IDENTIFIER = 'gatekeeper_token';
        this.URL = 'https://test-local';
        this.payload = {
            accountID: null,
            clientURL: null,
            browserID: null,
        };
        this.tab = new tab_1.Tab();
        fingerprintjs_1.default.load()
            .then((fp) => fp.get())
            .then(({ visitorId }) => (this.payload.browserID = visitorId));
  }
}`

**Comment by erdkse** [comment]
This is an outer library.  Why do you want to update it? @prachaporn

**Comment by prachaporn** [comment]
> This is an outer library. Why do you want to update it? @prachaporn

I used to update the login URL.

Please guide me on the steps to log in.

**Comment by erdkse** [comment]
this package usage is dropped. I am closing the issue.
