### ISSUE TITLE
Sidebar dont close in tablet when user tab an one option or suboption.

### ISSUE THREAD

**Issue by Victorsg1999** [erdkse/adminlte-3-react#89]
When user click in a option of sidebar in tablet, sidebar dont collapse.

This happens when you click on an option that has submenus.

**Comment by erdkse** [comment]
I started working on this issue, I will ping here when it is done @Victorsg1999

**Comment by erdkse** [comment]
Fixed, please check it out [here](https://www.erdkse.com/projects/preview?project=adminlte-react)
