### ISSUE TITLE
Firebase: how to specify the Firebase environment correctly?

### ISSUE THREAD

**Issue by stevennt** [erdkse/adminlte-3-react#97]
Hi, how to specify the Firebase config in the production correctly? I tried to put the below in but did not work. Tks.

<img width="603" alt="image" src="https://github.com/erdkse/adminlte-3-react/assets/32351181/ede0fb62-fa8d-43f5-bc42-252fbaf483cf">
<img width="604" alt="image" src="https://github.com/erdkse/adminlte-3-react/assets/32351181/adac6a95-ab66-47fd-869e-8c7674d2f2da">

The firebase config like this: 

<img width="332" alt="image" src="https://github.com/erdkse/adminlte-3-react/assets/32351181/443b0bdd-7fbd-48eb-94f0-25f8ba6a0f25">

`
VITE_NODE_ENV=production
VITE_FIREBASE_CONFIG={
  apiKey: "===============",
  authDomain: "=====saas.firebaseapp.com",
  projectId: "====-saas",
  storageBucket: "=======-saas.appspot.com",
  messagingSenderId: "=====",
  appId: "1:=====:web:4d222293978711fc8d96ea",
  measurementId: "G-P======"
};
`

**Comment by erdkse** [comment]
Hey @stevennt , It should be one line stringfied JSON. You can use JSON.stringfy(FIREBASE_CONFIG) and paste it in `.env` file.

**Comment by stevennt** [comment]
Works like a charm. Thanks!
